version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=media_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zoddstorm
    ports:
      - "5433:5432"
    networks:
      - media-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d media_db"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  media-network:

volumes:
  postgres_data:
