version: '3.8'
services:
  postgres:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    environment:
      POSTGRES_USER: zodd
      POSTGRES_PASSWORD: password
      POSTGRES_DB: media_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - media-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U zodd -d media_db']
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  postgres_data:
networks:
  media-network:
    name: media-network
